/**
 * Sequence definitions A–I: triggers, steps, default timing offsets, and
 * cancel conditions. Offsets are editable in the portal (SequenceStepConfig);
 * everything else here is the fixed shape of each sequence.
 *
 * Step kinds:
 *  EMAIL — auto-sent when due (subject to sequence enabled + master switch + dry run)
 *  DRAFT — pre-filled draft created as an internal task, a human sends it
 *  TASK  — internal task only, never emails anyone
 */

const H = 60;
const D = 24 * H;

export type CancelConditionKey =
  | "kickoff_booked"
  | "assets_received"
  | "care_decided";

export const CANCEL_CONDITIONS: Record<
  CancelConditionKey,
  { description: string }
> = {
  kickoff_booked: {
    description: "Cancelled when a kickoff call is booked (kickoff booked date set)",
  },
  assets_received: {
    description: "Cancelled when the client's content arrives (assets received date set)",
  },
  care_decided: {
    description:
      "Cancelled when care status changes from free (client converts or declines). If the client books the call from the earlier email, skip this step manually on their timeline.",
  },
};

export interface StepSource {
  key: string;
  label: string;
  kind: "EMAIL" | "DRAFT" | "TASK";
  templateKey?: string;
  offsetMinutes: number;
  offsetBounds: [number, number]; // sane editing bounds, minutes
  cancelCondition?: CancelConditionKey;
  taskTitle?: string; // {{token}} rendered
  taskDescription?: string;
  checklist?: string[];
  manualTrigger?: boolean; // not materialized from the anchor — the engine creates it on a specific event (e.g. care declined)
}

export interface SequenceSource {
  key: string;
  name: string;
  trigger: string; // human description shown in the editor
  anchorDescription: string;
  audience: "client" | "contractor" | "global";
  recurring?: boolean; // steps generated by the cron scanner, not materialized from a one-time trigger
  steps: StepSource[];
}

export const SEQUENCE_SOURCES: SequenceSource[] = [
  {
    key: "A",
    name: "Client onboarding",
    trigger: "Contract signed date is set",
    anchorDescription: "contract signed date",
    audience: "client",
    steps: [
      {
        key: "A1",
        label: "Welcome + roadmap + asset checklist",
        kind: "EMAIL",
        templateKey: "A1",
        offsetMinutes: 0,
        offsetBounds: [0, 1 * D],
      },
      {
        key: "A2",
        label: "Kickoff nudge",
        kind: "EMAIL",
        templateKey: "A2",
        offsetMinutes: 48 * H,
        offsetBounds: [12 * H, 14 * D],
        cancelCondition: "kickoff_booked",
      },
    ],
  },
  {
    key: "B",
    name: "Content collection",
    trigger: "Asset deadline is set (default: signing + 10 days, editable)",
    anchorDescription: "asset deadline",
    audience: "client",
    steps: [
      {
        key: "B1",
        label: "One week warning",
        kind: "EMAIL",
        templateKey: "B1",
        offsetMinutes: -7 * D,
        offsetBounds: [-30 * D, 0],
        cancelCondition: "assets_received",
      },
      {
        key: "B2",
        label: "Deadline day",
        kind: "EMAIL",
        templateKey: "B2",
        offsetMinutes: 0,
        offsetBounds: [0, 1 * D],
        cancelCondition: "assets_received",
      },
      {
        key: "B3",
        label: "Overdue decision",
        kind: "EMAIL",
        templateKey: "B3",
        offsetMinutes: 3 * D,
        offsetBounds: [1 * D, 30 * D],
        cancelCondition: "assets_received",
      },
    ],
  },
  {
    key: "C",
    name: "Friday update prompt",
    trigger: "Every Friday while a project is active (contract signed, not launched)",
    anchorDescription: "each Friday",
    audience: "client",
    recurring: true,
    steps: [
      {
        key: "C1",
        label: "Friday update draft for Chase",
        kind: "DRAFT",
        templateKey: "C1",
        offsetMinutes: 0,
        offsetBounds: [0, 0],
        taskTitle: "Friday update: {{project_name}}",
        taskDescription:
          "Human-filled 5 liner, never auto-sent. Fill the skeleton and send from your own inbox or the timeline.",
      },
    ],
  },
  {
    key: "D",
    name: "Close-out",
    trigger: "Launch date AND final payment date are both set",
    anchorDescription: "moment both dates are set",
    audience: "client",
    steps: [
      {
        key: "D1",
        label: "Completion summary",
        kind: "EMAIL",
        templateKey: "D1",
        offsetMinutes: 0,
        offsetBounds: [0, 3 * D],
      },
      {
        key: "D_referrals",
        label: "Referral names task",
        kind: "TASK",
        offsetMinutes: 0,
        offsetBounds: [0, 7 * D],
        taskTitle: "Log 2 referral names from handoff call for {{client}}",
      },
    ],
  },
  {
    key: "E",
    name: "Care conversion",
    trigger: "Launch date set, while care status is free",
    anchorDescription: "launch date",
    audience: "client",
    steps: [
      {
        key: "E_note30",
        label: "Care value note, month 1 (draft)",
        kind: "DRAFT",
        templateKey: "E1",
        offsetMinutes: 30 * D,
        offsetBounds: [7 * D, 60 * D],
        cancelCondition: "care_decided",
        taskTitle: "Fill Care value note for {{client}}",
        taskDescription: "Fill the 4 stat lines, then send. Draft is on the client's timeline.",
      },
      {
        key: "E_note60",
        label: "Care value note, month 2 (draft)",
        kind: "DRAFT",
        templateKey: "E1",
        offsetMinutes: 60 * D,
        offsetBounds: [30 * D, 90 * D],
        cancelCondition: "care_decided",
        taskTitle: "Fill Care value note for {{client}}",
        taskDescription: "Fill the 4 stat lines, then send. Draft is on the client's timeline.",
      },
      {
        key: "E_note80",
        label: "Care value note, month 3 (draft, 10 days before period ends)",
        kind: "DRAFT",
        templateKey: "E1",
        offsetMinutes: 80 * D,
        offsetBounds: [60 * D, 90 * D],
        cancelCondition: "care_decided",
        taskTitle: "Fill Care value note for {{client}}",
        taskDescription: "Fill the 4 stat lines, then send. Draft is on the client's timeline.",
      },
      {
        key: "E_call70",
        label: "Conversion call booking email",
        kind: "EMAIL",
        templateKey: "E2",
        offsetMinutes: 70 * D,
        offsetBounds: [30 * D, 90 * D],
        cancelCondition: "care_decided",
      },
      {
        key: "E_decision80",
        label: "Decision email",
        kind: "EMAIL",
        templateKey: "E3",
        offsetMinutes: 80 * D,
        offsetBounds: [40 * D, 95 * D],
        cancelCondition: "care_decided",
      },
      {
        key: "E_owners_manual",
        label: "On decline: send Owner's Manual (task)",
        kind: "TASK",
        offsetMinutes: 0,
        offsetBounds: [0, 7 * D],
        manualTrigger: true,
        taskTitle: "Send Website Owner's Manual to {{client}}",
        taskDescription: "Client declined Care. Send the manual and the self-hosting handoff list.",
      },
      {
        key: "E_reapproach",
        label: "On decline: re-approach reminder in 6 months (task)",
        kind: "TASK",
        offsetMinutes: 180 * D,
        offsetBounds: [90 * D, 366 * D],
        manualTrigger: true,
        taskTitle: "Re-approach {{client}} about Care",
        taskDescription: "6 months since they declined Care. Check how the site is holding up and offer again.",
      },
    ],
  },
  {
    key: "F",
    name: "Care client check-ins",
    trigger: "Care status becomes paying",
    anchorDescription: "date care went paying",
    audience: "client",
    steps: [
      {
        key: "F_30",
        label: "30 day check-in task",
        kind: "TASK",
        offsetMinutes: 30 * D,
        offsetBounds: [7 * D, 60 * D],
        taskTitle: "Book 30-day check-in with {{client}}",
        taskDescription: "15 minutes. How is the site doing, anything they want changed.",
      },
      {
        key: "F_60",
        label: "60 day check-in task",
        kind: "TASK",
        offsetMinutes: 60 * D,
        offsetBounds: [30 * D, 90 * D],
        taskTitle: "Book 60-day check-in with {{client}}",
        taskDescription: "15 minutes. How is the site doing, anything they want changed.",
      },
      {
        key: "F_90",
        label: "90 day check-in task",
        kind: "TASK",
        offsetMinutes: 90 * D,
        offsetBounds: [60 * D, 120 * D],
        taskTitle: "Book 90-day check-in with {{client}}",
        taskDescription:
          "15 minutes. How is the site doing, anything they want changed. Repeats quarterly from here.",
      },
      // After F_90, the cron keeps scheduling F_quarterly occurrences every 90 days while paying.
      {
        key: "F_quarterly",
        label: "Quarterly check-in task (repeats)",
        kind: "TASK",
        offsetMinutes: 180 * D,
        offsetBounds: [90 * D, 366 * D],
        taskTitle: "Book quarterly check-in with {{client}}",
        taskDescription: "15 minutes. Repeats every 90 days while Care is paying.",
      },
    ],
  },
  {
    key: "G",
    name: "Quarterly recap broadcast",
    trigger: "Calendar, every 3 months",
    anchorDescription: "quarter start",
    audience: "global",
    recurring: true,
    steps: [
      {
        key: "G1",
        label: "Recap draft broadcast (Chase edits results lines, then sends)",
        kind: "DRAFT",
        templateKey: "G1",
        offsetMinutes: 0,
        offsetBounds: [0, 0],
        taskTitle: "Quarterly recap: edit results lines and send broadcast",
        taskDescription:
          "Draft goes to every past or current client and every partner. Edit the [RESULTS] lines on the Automations page, then send. Never sends itself.",
      },
    ],
  },
  {
    key: "H",
    name: "Partner touches",
    trigger: "Role is partner, quarterly",
    anchorDescription: "each quarter",
    audience: "client",
    recurring: true,
    steps: [
      {
        key: "H_touch",
        label: "Quarterly partner touch task",
        kind: "TASK",
        offsetMinutes: 0,
        offsetBounds: [0, 0],
        taskTitle: "Quarterly touch: {{partner}}",
      },
    ],
  },
  {
    key: "I",
    name: "Contractor onboarding",
    trigger: "Agreement signed date set on a contractor",
    anchorDescription: "agreement signed date",
    audience: "contractor",
    steps: [
      {
        key: "I_day0",
        label: "Before day 1 checklist",
        kind: "TASK",
        offsetMinutes: 0,
        offsetBounds: [0, 7 * D],
        taskTitle: "Before day 1: {{first_name}}",
        checklist: [
          "Password manager seat (least access)",
          "Brand kit shared",
          "Copy rules shared",
          "Tool access",
          "Month 1 deliverable list sent",
        ],
      },
      {
        key: "I_day7",
        label: "Week 1 review",
        kind: "TASK",
        offsetMinutes: 7 * D,
        offsetBounds: [3 * D, 14 * D],
        taskTitle: "Week 1 review: {{first_name}}",
        taskDescription: "20 min, what was confusing.",
      },
      {
        key: "I_day14",
        label: "Week 2 check",
        kind: "TASK",
        offsetMinutes: 14 * D,
        offsetBounds: [7 * D, 21 * D],
        taskTitle: "Week 2 check: {{first_name}}",
        taskDescription: "Owns one calendar end to end, 3+ SOP Looms on board.",
      },
      {
        key: "I_day30",
        label: "Day 30 review",
        kind: "TASK",
        offsetMinutes: 30 * D,
        offsetBounds: [21 * D, 45 * D],
        taskTitle: "Day 30 contractor review: {{first_name}}",
        taskDescription: "Expect around 25% output at this point.",
      },
      {
        key: "I_day60",
        label: "Day 60 review",
        kind: "TASK",
        offsetMinutes: 60 * D,
        offsetBounds: [45 * D, 75 * D],
        taskTitle: "Day 60 contractor review: {{first_name}}",
        taskDescription: "Reduce review sampling if quality holds.",
      },
      {
        key: "I_day90",
        label: "Day 90 review",
        kind: "TASK",
        offsetMinutes: 90 * D,
        offsetBounds: [75 * D, 120 * D],
        taskTitle: "Day 90 contractor review: {{first_name}}",
        taskDescription: "Expand, hold or exit decision. Run the Scheinselbständigkeit checklist.",
      },
      {
        key: "I_weekly",
        label: "Weekly review (repeats on the contractor's review day)",
        kind: "TASK",
        offsetMinutes: 0,
        offsetBounds: [0, 0],
        taskTitle: "Weekly contractor review: {{first_name}}",
        taskDescription:
          "Agenda: shipped vs list (counts) · one great one to change · blockers · next week's list confirmed in writing · 5 min skill note.",
      },
    ],
  },
];

export const SEQUENCE_SOURCE_BY_KEY: Record<string, SequenceSource> = Object.fromEntries(
  SEQUENCE_SOURCES.map((s) => [s.key, s])
);

export function stepSource(sequenceKey: string, stepKey: string): StepSource | null {
  return SEQUENCE_SOURCE_BY_KEY[sequenceKey]?.steps.find((s) => s.key === stepKey) || null;
}
